### ISSUE TITLE
Improve output of the AL process

### ISSUE THREAD

**Issue by J535D165** [msdslab/automated-systematic-review#25] opened 2019-03-11 09:45 UTC
Improve the Logger class https://github.com/msdslab/automated-systematic-review/blob/036e89b292aebe0a838b4068d060e519a2172dbb/asr/utils.py#L82-L160

Implement:

 - Store prediction results
 -

**Comment by qubixes** [comment] 2019-08-21 13:03
Isn't this a duplicate of #30?

**Closed** 2019-10-08 14:29 UTC
