### ISSUE TITLE
UTF-8 Encoding troubles

### ISSUE THREAD

**Issue by eduh** [msdslab/automated-systematic-review#59] opened 2019-06-28 10:45 UTC
When downloading a RIS file from scopus.com it looks like the python lib is not able to handle the file. Workaround is to convert the RIS file to good old ASCII and then problem is solved.

To repeat the error , just search scopus for anything and download 2000 records to RIS format and start the asr.
Error is:
"c:\users\hacke101\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3613: character maps to <undefined>

**Comment by qubixes** [comment] 2019-07-12 08:21
Thanks for bringing the issue to our attention. 

Personally, I can't reproduce the error on OS X (I downloaded a random 2K line RIS file from scopus and it worked fine for me).

Could you provide a sample?

**Comment by J535D165** [comment] 2019-07-12 08:25
@qubixes Encoding is platform specific. This is a common issue with Python on Windows. I think I know the solution and I'm working on a fix with unit test.

**Comment by eduh** [comment] 2019-07-16 07:36
I have tested the software on windows 10.  Attached a RIS file for reproducing the error.
[scopus.ris.zip](https://github.com/msdslab/automated-systematic-review/files/3395836/scopus.ris.zip)

**Comment by qubixes** [comment] 2019-11-21 21:20
This should be fixed with the latest commit. Feel free to reopen if this is not the case.

**Closed by qubixes** 2019-11-21 21:20 UTC
Labels: bug
